
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8801/eureka/
  instance:
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
    prefer-ip-address: true
server:
  port: 8803
spring:
  application:
    name: ribbon-consumer